project_name: shopify-csv-download

release:
  github:
    owner: kishaningithub
    name: shopify-csv-download

before:
  hooks:
  - go mod download

builds:
- main: ./cmd/shopify-csv-download/main.go
  binary: shopify-csv-download
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64

brews:
  - name: shopify-csv-download
    github:
      owner: kishaningithub
      name: homebrew-tap
    url_template: "https://github.com/kishaningithub/shopify-csv-download/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://github.com/kishaningithub/shopify-csv-download"
    description: "Download a shopify site in a csv format that the shopify importer understands"