sudo: false
language: go
go:
- 1.14.6
- 1.15
install:
- go mod download
- curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
script:
- go test -v ./...
- ./bin/goreleaser check
after_success:
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
